Conf0 = CONFIG,

Deps = case os:getenv("NOVA_BRANCH", "master") of
            "master" -> {deps, [
              {nova, ".*", {git, "https://github.com/novaframework/nova.git", {branch, "master"}}}
             ]};
             NovaBranch -> {deps, [
              {nova, ".*", {git, "https://github.com/novaframework/nova.git", {branch, NovaBranch}}}
             ]}
            end,
Conf1 = proplists:delete(deps, Conf0),

[Deps|Conf1].

