name: Build and test

on: [repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Erlang/OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    strategy:
      fail-fast: false
      matrix:
        otp: ['24.1.3', '25.1.1', '26.1']
        rebar3: ['3.22.0']

    steps:
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        rebar3-version: ${{matrix.rebar3}}
        version-type: strict
    - name: Compile
      run: rebar3 compile
    - name: Event Information
      run: |
        echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
    - name: PONG - Dispatch response to received PING
      if: github.event.action == 'start_test'
      run: rebar3 ct