name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Erlang/OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    strategy:
      fail-fast: false
      matrix:
        otp: ['26.1', '27.1', '28.0']
        rebar3: ['3.25.0']

    steps:
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        rebar3-version: ${{matrix.rebar3}}
        version-type: strict
    - name: Compile
      run: rebar3 compile
    - name: Test
      run: rebar3 ct