name: Run Nova Request App

on:
  workflow_call:
    inputs:
      nova_branch:
        required: true
        type: string
        default: main

env:
  NOVA_BRANCH: "${{ inputs.nova_branch }}"
jobs:
  run-nra:
    runs-on: ubuntu-22.04
    name: Erlang/OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    strategy:
      fail-fast: false
      matrix:
        otp: ['25.1.1', '26.1', '27.0']
        rebar3: ['3.23.0']

    steps:
    - uses: actions/checkout@v4
      with:
        repository: novaframework/nova_request_app
        ref: main
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        rebar3-version: ${{matrix.rebar3}}
        version-type: strict
    - name: Test
      run: NOVA_BRANCH="${{ inputs.nova_branch }}" rebar3 ct



